services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
      
  web:
    build: .
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/home/app/web
    ports:
      - '3000:3000'
    depends_on:
      - db
     

volumes:
  psql-data: