services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data

  web:
    tty: true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bash bin/entrypoint.sh"

    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/home/app/web
    ports:
      - '3000:3000'
    depends_on:
      - db


volumes:
  psql-data: