ARG RUBY_VERSION=3.4.2
ARG DISTRO=bullseye

FROM ruby:${RUBY_VERSION}-slim-${DISTRO}

RUN apt update && apt install -y --no-install-recommends \
    chromium \
    chromium-driver \
    build-essential \
    libpq-dev \
    libyaml-dev \
    libvips42 \
    watchman


WORKDIR /home/app/web

COPY Gemfile Gemfile.lock ./

RUN gem update --system

RUN gem install foreman

RUN bundle install

COPY . . 

CMD ["bin/dev"]

EXPOSE 3000