default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:  <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: quadro_vagas_rb_development

test:
  <<: *default
  database: quadro_vagas_rb_test


production:
  primary: &primary_production
    <<: *default
    database: quadro_vagas_rb_production
    username: quadro_vagas_rb
    password: <%= ENV["QUADRO_VAGAS_RB_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: quadro_vagas_rb_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quadro_vagas_rb_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quadro_vagas_rb_production_cable
    migrations_paths: db/cable_migrate
