default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  primary:
    <<: *default
    database: quadrovagas-development
  queue:
    <<: *default
    database: quadrovagas-development_queue
    migrations_paths: db/queue_migrate



test:
  primary:
    <<: *default
    database: quadrovagas-test
  queue:
    <<: *default
    database: quadrovagas-test_queue
    migrations_paths: db/queue_migrate
  

production:
  primary:
     <<: *default
     database: quadrovagas-production
  queue:
    <<: *default
    database: quadrovagas-production
    migrations_paths: db/queue_migrate
 